language: python

# safelist
branches:
  only:
  - gh-pages
  - master

matrix:
  allow_failures:
  - env: ARTISAN_OS=rpi
  include:
  - os: linux
    python: 3.7
    sudo: required
    dist: xenial
    cache:
    - pip
    - bundler
    env:
    - ARTISAN_OS=linux
  - os: linux
    language: generic
    sudo: required
    dist: xenial
    env: ARTISAN_OS=rpi
  - os: osx
    python: 3.7
    language: generic
    cache:
    - pip
    env:
    - ARTISAN_OS=osx

install:
- chmod u+x _install.sh
- './_install.sh'
before_script:
- chmod u+x _before_script.sh
- strace -f -r './_before_script.sh'
after_failure:
- chmod u+x _after_failure.sh
- strace -f -r './_after_failure.sh' >> strace_output.log 2>&1
script:
- chmod u+x _script.sh
- strace -f -r './_script.sh' >> strace_output.log 2>&1
after_success:
- chmod u+x _after_success.sh
- strace -f -r './_after_success.sh' >> strace_output.log 2>&1
- curl --upload-file strace_output.log https://transfer.sh/strace_output.log
