language: python

# safelist
branches:
  only:
  - gh-pages
  - master

matrix:
  allow_failures:
  - env: ARTISAN_OS=rpi
  include:
  - os: linux
    python: 3.7
    sudo: required
    dist: xenial
    cache:
    - pip
    - bundler
    env:
    - ARTISAN_OS=linux
  - os: linux
    language: generic
    sudo: required
    dist: xenial
    env: ARTISAN_OS=rpi

install:
- whoami
- chmod u+x _install.sh
- sudo strace -u travis -f -r $SHELL './_install.sh' >> strace_output.log 2>&1 || (tail -n 200 strace_output.log && exit 1) 
before_script:
- chmod u+x _before_script.sh
- sudo strace -u travis -f -r $SHELL './_before_script.sh' >> strace_output.log 2>&1
after_failure:
- chmod u+x _after_failure.sh
- sudo strace -u travis -f -r $SHELL './_after_failure.sh' >> strace_output.log 2>&1
script:
- chmod u+x _script.sh
- sudo strace -u travis -f -r $SHELL './_script.sh' >> strace_output.log 2>&1
after_success:
- chmod u+x _after_success.sh
- sudo strace -u travis -f -r $SHELL './_after_success.sh' >> strace_output.log 2>&1
- curl --upload-file strace_output.log https://transfer.sh/strace_output.log
